### ISSUE TITLE
Icone do GPS

### ISSUE THREAD

**Issue by caiomoura1994** [dfiaes/sgMapApp#5]
Caso GPS esteja desligado, o icone deverá ser a imagem de um ponto de interrogação com a ultima posição conhecida do usuário. Caso o GPS esteja ligado, a imagem do icone deverá ser outra que não o sinal de interrogação.

**Comment by caiomoura1994** [comment]
```
mMap.addMarker(new MarkerOptions()
      .icon(BitmapDescriptorFactory.fromResource(R.drawable.current_position_tennis_ball))
);

```

**Comment by dfiaes** [comment]
feito
